// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEzcmvzS2r25DTCRD_m0S7KL6P_Zr8LfQ',
    appId: '1:645546989385:web:f5f71f5e98df5f287c2c98',
    messagingSenderId: '645546989385',
    projectId: 'examen-flutter-2c67f',
    authDomain: 'examen-flutter-2c67f.firebaseapp.com',
    storageBucket: 'examen-flutter-2c67f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9gABjOERLtYKJ0dzbA8Gh_R-YBg1PxOk',
    appId: '1:645546989385:android:d27d4d06c9fad9827c2c98',
    messagingSenderId: '645546989385',
    projectId: 'examen-flutter-2c67f',
    storageBucket: 'examen-flutter-2c67f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW9578FhZFv1Ty334Kgh8x1woEki3xJcw',
    appId: '1:645546989385:ios:ac541db5f861bd037c2c98',
    messagingSenderId: '645546989385',
    projectId: 'examen-flutter-2c67f',
    storageBucket: 'examen-flutter-2c67f.appspot.com',
    iosClientId: '645546989385-d7csb62qsaveqihncjmpf9q6fkhic2k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW9578FhZFv1Ty334Kgh8x1woEki3xJcw',
    appId: '1:645546989385:ios:ac541db5f861bd037c2c98',
    messagingSenderId: '645546989385',
    projectId: 'examen-flutter-2c67f',
    storageBucket: 'examen-flutter-2c67f.appspot.com',
    iosClientId: '645546989385-d7csb62qsaveqihncjmpf9q6fkhic2k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEzcmvzS2r25DTCRD_m0S7KL6P_Zr8LfQ',
    appId: '1:645546989385:web:c7be1c08837e79857c2c98',
    messagingSenderId: '645546989385',
    projectId: 'examen-flutter-2c67f',
    authDomain: 'examen-flutter-2c67f.firebaseapp.com',
    storageBucket: 'examen-flutter-2c67f.appspot.com',
  );
}
